# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xsql < Formula
  desc "AI-first cross-database CLI tool with SSH proxy support"
  homepage "https://github.com/zx06/xsql"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zx06/xsql/releases/download/v0.0.5/xsql_0.0.5_darwin_amd64.tar.gz"
      sha256 "ae8be4fdb6d522d321616612504505f0525b88675864cce91adf03e28390bd29"

      def install
        bin.install "xsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zx06/xsql/releases/download/v0.0.5/xsql_0.0.5_darwin_arm64.tar.gz"
      sha256 "ab8c49d4baf51d8d74033ca1aba66b7251d6ff8aeddf358126683dbfc800c9db"

      def install
        bin.install "xsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zx06/xsql/releases/download/v0.0.5/xsql_0.0.5_linux_amd64.tar.gz"
      sha256 "0d322e31b924cf355c8588faa1163737966d1abaff0273addb7f017940955f9c"
      def install
        bin.install "xsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zx06/xsql/releases/download/v0.0.5/xsql_0.0.5_linux_arm64.tar.gz"
      sha256 "9b9ac3a163091ba8b74abc2cc24a192b8549bc8050216f9f672e0cd1702c990c"
      def install
        bin.install "xsql"
      end
    end
  end

  test do
    system "#{bin}/xsql", "version"
  end
end
