# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xsql < Formula
  desc "AI-first cross-database CLI tool with SSH proxy support"
  homepage "https://github.com/zx06/xsql"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zx06/xsql/releases/download/v1.0.0/xsql_1.0.0_darwin_amd64.tar.gz"
      sha256 "1d3cce4e2b2b440eb7189e3716523a0e35700df8e75097c06aa5ea44a931be90"

      define_method(:install) do
        bin.install "xsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zx06/xsql/releases/download/v1.0.0/xsql_1.0.0_darwin_arm64.tar.gz"
      sha256 "f7fb6c6bccfa2b671f932d47fe935ca9d64e17540ac32b9505245167e1f8cbd5"

      define_method(:install) do
        bin.install "xsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zx06/xsql/releases/download/v1.0.0/xsql_1.0.0_linux_amd64.tar.gz"
      sha256 "42a3d5b15ecad18bc4574b727df7b7abf207c6ab1f77ee647471b813480051dc"
      define_method(:install) do
        bin.install "xsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zx06/xsql/releases/download/v1.0.0/xsql_1.0.0_linux_arm64.tar.gz"
      sha256 "fc8de5348065e21225192063f01a39709cf50fc39372acc465617d48ffcc92fc"
      define_method(:install) do
        bin.install "xsql"
      end
    end
  end

  test do
    system "#{bin}/xsql", "version"
  end
end
